# frozen_string_literal: true

module Shadcnrb
  # Base class for the Builder. Applications subclass this as `Shadcnrb::Builder`
  # in `app/components/shadcnrb/builder.rb` (generated by `shadcnrb:install`) and
  # include component modules into the subclass. Keeping the base distinct means
  # the app-level Builder can safely reopen/extend without shadowing the gem.
  class BaseBuilder
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::UrlHelper
    include ActionView::Helpers::OutputSafetyHelper

    # Exposed so component classes can reach Rails view helpers directly
    # when the Builder itself has wrapped the name (e.g. `button_to` on
    # Builder delegates to `Shadcnrb::Button#button_to`, which must be able
    # to call the original UrlHelper without recursing).
    attr_reader :view_context

    delegate :render, :capture, :form_with, :fields_for, :current_page?, to: :@view_context
    delegate_missing_to :@view_context

    def initialize(view_context)
      @view_context = view_context
    end
  end
end
